# -*- coding: utf-8 -*-
"""
The Glorious pokedex
"""

dex = {
       1 : {
           'name': 'Peblet',
           'type1': 'Rock',
           'type2': 'None',
           'hp':40,
           'atk':75,
           'def':35,
           'spa':55,
           'spd':25,
           'spe':80,
           'sprite':'graphics/sprites/pokemon/001-PEBLET.png',
           'ability':['Adaptability'],
           'itempool':['none'],
           'evolution':[[2, 'level', 16]],
           'movepool' : {
               1:'Tackle',
               3:'Howl',
               7:'Rock Throw',
               9:'Rock Polish',
               13:'Rock Tomb',
               14:'Rock Slide',
               15:'Take Down',
               19:'Boulder Toss',
               21:'Sandstorm',
               25:'Accelerock',
               27:'Double Edge',
               31:'Cliff Dive',
               34:'Seed Bomb',
               42:'Stealth Rock',
               },
           'tms' : [
               'Rock Smash',
               'Rock Climb'
               'Rock Slide',
               'Boulder Toss',
               'Sandstorm',
               'Grassy Glide'
               ]
           },
       2: {
           'name': 'Robilly',
           'type1': 'Rock',
           'type2': 'None',
           'hp':60,
           'atk':95,
           'def':45,
           'spa':80,
           'spd':40,
           'spe':100,
           'sprite':'graphics/sprites/pokemon/002-ROBILLY.png',
           'ability':['Adaptability'],
           'itempool':['none'],
           'evolution':[[3, 'level', 32]],
           'movepool' : {
               1:'Tackle',
               3:'Howl',
               7:'Rock Throw',
               9:'Rock Polish',
               13:'Rock Tomb',
               14:'Rock Slide',
               15:'Take Down',
               19:'Boulder Toss',
               21:'Sandstorm',
               25:'Accelerock',
               27:'Double Edge',
               31:'Cliff Dive',
               34:'Seed Bomb',
               42:'Stealth Rock',
               },
           'tms' : [
               'Rock Smash',
               'Rock Climb'
               'Rock Slide',
               'Boulder Toss',
               'Sandstorm',
               'Grassy Glide'
               ]
           },
       3: {
           'name': 'Cragclimb',
           'type1': 'Rock',
           'type2': 'None',
           'hp':75,
           'atk':135,
           'def':50,
           'spa':75,
           'spd':50,
           'spe':145,
           'sprite':'graphics/sprites/pokemon/003-CRAGCLIMB.png',
           'ability':['Adaptability'],
           'itempool':['none'],
           'evolution':[['none']],
           'movepool' : {
               1:'Tackle',
               3:'Howl',
               7:'Rock Throw',
               9:'Rock Polish',
               13:'Rock Tomb',
               14:'Rock Slide',
               15:'Take Down',
               19:'Boulder Toss',
               21:'Sandstorm',
               25:'Accelerock',
               27:'Double Edge',
               31:'Cliff Dive',
               34:'Seed Bomb',
               42:'Stealth Rock',
               },
           'tms' : [
               'Rock Smash',
               'Rock Climb'
               'Rock Slide',
               'Boulder Toss',
               'Sandstorm',
               'Grassy Glide'
               ]
           },
       4: {
           'name': 'Guardil',
           'type1': 'Steel',
           'type2': 'None',
           'hp':70,
           'atk':40,
           'def':65,
           'spa':35,
           'spd':65,
           'spe':35,
           'sprite':'graphics/sprites/pokemon/004-GUARDIL.png',
           'ability':['Adaptive Shielding'],
           'itempool':['none'],
           'evolution':[[5, 'level', 16]],
           'movepool' : {
               1:['Pound', 'Metal Sound'],
               7:'Smart Strike',
               10:'Iron Defense',
               16:'Iron Head',
               19:'Recover',
               20:'Shadow Sneak',
               25:'Kings Shield',
               28:'Taunt',
               30:'Body Press',
               34:'Spikes',
               37:'Toxic',
               43:'Block',
               },
           'tms' : [
               'Rock Smash',
               'Strength'
               'Toxic',
               'Taunt',
               'Protect',
               ]
           },
       5: {
           'name': 'Barishield',
           'type1': 'Steel',
           'type2': 'None',
           'hp':90,
           'atk':65,
           'def':80,
           'spa':55,
           'spd':80,
           'spe':50,
           'sprite':'graphics/sprites/pokemon/005-BARISHIELD.png',
           'ability':['Adaptive Shielding'],
           'itempool':['none'],
           'evolution':[[6, 'level', 32]],
           'movepool' : {
               1:['Pound', 'Metal Sound'],
               7:'Smart Strike',
               10:'Iron Defense',
               16:'Iron Head',
               19:'Recover',
               20:'Shadow Sneak',
               25:'Kings Shield',
               28:'Taunt',
               30:'Body Press',
               34:'Spikes',
               37:'Toxic',
               43:'Block',
               },
           'tms' : [
               'Rock Smash',
               'Strength'
               'Toxic',
               'Taunt',
               'Protect',
               ]
           },
       6: {
           'name': 'Citadelord',
           'type1': 'Steel',
           'type2': 'None',
           'hp':110,
           'atk':80,
           'def':115,
           'spa':55,
           'spd':115,
           'spe':55,
           'sprite':'graphics/sprites/pokemon/006-CITADELORD.png',
           'ability':['Adaptive Shielding'],
           'itempool':['none'],
           'evolution':[['none']],
           'movepool' : {
               1:['Pound', 'Metal Sound'],
               7:'Smart Strike',
               10:'Iron Defense',
               16:'Iron Head',
               19:'Recover',
               20:'Shadow Sneak',
               25:'Kings Shield',
               28:'Taunt',
               30:'Body Press',
               34:'Spikes',
               37:'Toxic',
               43:'Block',
               },
           'tms' : [
               'Rock Smash',
               'Strength'
               'Toxic',
               'Taunt',
               'Protect',
               ]
           },
       7: {
           'name': 'Flicklit',
           'type1': 'Fire',
           'type2': 'None',
           'hp':70,
           'atk':40,
           'def':45,
           'spa':70,
           'spd':50,
           'spe':35,
           'sprite':'graphics/sprites/pokemon/007-FLICKLIT.png',
           'ability':['Magic Guard'],
           'itempool':['none'],
           'evolution':[[8, 'level', 16]],
           'movepool' : {
               1:'Pound',
               4:'Poison Powder',
               7:'Ember',
               10:'Poison Sting',
               13:'Bubble',
               16:'Fire Spin',
               19:'Rapid Spin',
               22:'Acid Armor',
               25:'Sludge Wave',
               28:'Flamethrower',
               31:'Overheat',
               34:'Nasty Plot',
               37:'Sunny Day',
               40:'Hydro Pump',
               },
           'tms' : [
               'Dive',
               'Waterfall'
               'Toxic',
               'Surf',
               'Protect',
               ]
           },
       8: {
           'name': 'Scorch',
           'type1': 'Fire',
           'type2': 'None',
           'hp':90,
           'atk':50,
           'def':65,
           'spa':100,
           'spd':70,
           'spe':45,
           'sprite':'graphics/sprites/pokemon/008-SCORCH.png',
           'ability':['Magic Guard'],
           'itempool':['none'],
           'evolution':[[9, 'level', 32]],
           'movepool' : {
               1:'Pound',
               4:'Poison Powder',
               7:'Ember',
               10:'Poison Sting',
               13:'Bubble',
               16:'Fire Spin',
               19:'Rapid Spin',
               22:'Acid Armor',
               25:'Sludge Wave',
               28:'Flamethrower',
               31:'Overheat',
               34:'Nasty Plot',
               37:'Sunny Day',
               40:'Hydro Pump',
               },
           'tms' : [
               'Dive',
               'Waterfall'
               'Toxic',
               'Surf',
               'Protect',
               ]
           },
       9: {
           'name': 'Embergeon',
           'type1': 'Fire',
           'type2': 'None',
           'hp':130,
           'atk':55,
           'def':70,
           'spa':160,
           'spd':70,
           'spe':45,
           'sprite':'graphics/sprites/pokemon/009-EMBERGEON.png',
           'ability':['Magic Guard'],
           'itempool':['none'],
           'evolution':[['none']],
           'movepool' : {
               1:'Pound',
               4:'Poison Powder',
               7:'Ember',
               10:'Poison Sting',
               13:'Bubble',
               16:'Fire Spin',
               19:'Rapid Spin',
               22:'Acid Armor',
               25:'Sludge Wave',
               28:'Flamethrower',
               31:'Overheat',
               34:'Nasty Plot',
               37:'Sunny Day',
               40:'Hydro Pump',
               },
           'tms' : [
               'Dive',
               'Waterfall'
               'Toxic',
               'Surf',
               'Protect',
               ]
           },
       10: {
           'name': 'Mourmoss',
           'type1': 'Ghost',
           'type2': 'Normal',
           'hp':55,
           'atk':30,
           'def':65,
           'spa':35,
           'spd':65,
           'spe':30,
           'sprite':'graphics/sprites/pokemon/010-MOURMOSS.png',
           'ability':['Rain Dish', 'Swift Swim'],
           'itempool':['Damp Rock'],
           'evolution':[[11, 'level', 14]],
           'movepool' : {
               1:'Tackle',
               2:'Rain Dance',
               5:'Astonish',
               7:'Absorb',
               9:'Gust',
               12:'Will-O-Wisp',
               13:'Whirlpool',
               14:'Ingrain',
               16:'Swift',
               20:'Recover',
               23:'Giga Drain',
               26:'Worry Seed',
               30:'Hex',
               32:'Hyper Voice',
               35:'Hurricane',
               40:'Hyper Beam',
               43:'Night Terror',
               },
           'tms' : [
               'Dive',
               'Waterfall'
               'Will-O-Wisp',
               'Surf',
               'Strength',
               'Protect',
               ]
           },
       11: {
           'name': 'Velovarre',
           'type1': 'Ghost',
           'type2': 'Normal',
           'hp':90,
           'atk':40,
           'def':100,
           'spa':55,
           'spd':100,
           'spe':30,
           'sprite':'graphics/sprites/pokemon/011-VELOVARRE.png',
           'ability':['Rain Dish', 'Swift Swim'],
           'itempool':['Damp Rock'],
           'evolution':[[12, 'level', 28]],
           'movepool' : {
               1:'Tackle',
               2:'Rain Dance',
               5:'Astonish',
               7:'Absorb',
               9:'Gust',
               12:'Will-O-Wisp',
               13:'Whirlpool',
               14:'Ingrain',
               16:'Swift',
               20:'Recover',
               23:'Giga Drain',
               26:'Worry Seed',
               30:'Hex',
               32:'Hyper Voice',
               35:'Hurricane',
               40:'Hyper Beam',
               43:'Night Terror',
               },
           'tms' : [
               'Dive',
               'Waterfall'
               'Will-O-Wisp',
               'Surf',
               'Strength',
               'Protect',
               ]
           },
       12: {
           'name': 'Gloomhorn',
           'type1': 'Ghost',
           'type2': 'Normal',
           'hp':115,
           'atk':40,
           'def':120,
           'spa':75,
           'spd':120,
           'spe':40,
           'sprite':'graphics/sprites/pokemon/012-GLOOMHORN.png',
           'ability':['Rain Dish', 'Swift Swim'],
           'itempool':['Damp Rock'],
           'evolution':[['none']],
           'movepool' : {
               1:'Tackle',
               2:'Rain Dance',
               5:'Astonish',
               7:'Absorb',
               9:'Gust',
               12:'Will-O-Wisp',
               13:'Whirlpool',
               14:'Ingrain',
               16:'Swift',
               20:'Recover',
               23:'Giga Drain',
               26:'Worry Seed',
               30:'Hex',
               32:'Hyper Voice',
               35:'Hurricane',
               40:'Hyper Beam',
               43:'Night Terror',
               },
           'tms' : [
               'Dive',
               'Waterfall'
               'Will-O-Wisp',
               'Surf',
               'Strength',
               'Protect',
               ]
           },
       13: {
           'name': 'Weedle',
           'type1': 'Bug',
           'type2': 'None',
           'hp':40,
           'atk':35,
           'def':30,
           'spa':20,
           'spd':20,
           'spe':50,
           'sprite':'graphics/sprites/pokemon/013-WEEDLE.png',
           'ability':['Shield Dust', 'Sand Rush'],
           'itempool':['Eviolite'],
           'evolution':[[14, 'level', 7]],
           'movepool' : {
               1:'Poison Sting',
               2:'String Shot',
               5:'Bug Bite',
               },
           'tms' : [
               'Protect',
               ]
           },
       14: {
           'name': 'Kakuna',
           'type1': 'Bug',
           'type2': 'Rock',
           'hp':80,
           'atk':50,
           'def':150,
           'spa':25,
           'spd':95,
           'spe':35,
           'sprite':'graphics/sprites/pokemon/014-KAKUNA.png',
           'ability':['Shield Dust', 'Sand Stream'],
           'itempool':['Eviolite'],
           
           'evolution':[[15, 'level', 10]],
           'movepool' : {
               1:'Harden',
               2:'Pound',
               8:'Iron Defense',
               12:'Body Press',
               13:'Stealth Rock',
               15:'Night Shade',
               17:'Rock Slide',
               20:'Shore Up',
               23:'Infestation',
               },
           'tms' : [
               'Rock Smash',
               'Strength',
               'Protect',
               ]
           },
       15: {
           'name': 'Beedrill',
           'type1': 'Bug',
           'type2': 'Rock',
           'hp':65,
           'atk':110,
           'def':90,
           'spa':60,
           'spd':70,
           'spe':110,
           'sprite':'graphics/sprites/pokemon/015-BEEDRIL.png',
           'ability':['Rock Head', 'Sand Stream'],
           'itempool':['King\'s Rock'],
           'evolution':[['none']],
           'movepool' : {
               1:'Twineedle',
               2:'Fury Attack',
               10:'Rock Throw',
               15:'Rock Blast',
               16:'Quiver Dance',
               18:'Pursuit',
               20:'Boulder Toss',
               22:'Megahorn',
               24:'Swords Dance',
               28:'Leech Life',
               29:'Giga Drain',
               31:'Sandstorm',
               33:'Infestation',
               40:'Bug Buzz',
               45:'Head Smash',
               },
           'tms' : [
               'Rock Smash',
               'Strength',
               'Protect',
               ]
           },
       16: {
           'name': 'Peepunch',
           'type1': 'Flying',
           'type2': 'Fighting',
           'hp':45,
           'atk':60,
           'def':40,
           'spa':25,
           'spd':35,
           'spe':100,
           'sprite':'graphics/sprites/pokemon/016-PEEPUNCH.png',
           'ability':['Scrappy', 'Speed Boost'],
           'itempool':['Focus Sash'],
           'evolution':[[17, 'level', 16]],
           'movepool' : {
               1:'Tackle',
               5:'Sand Attack',
               9:'Mach Punch',
               13:'Quick Attack',
               17:'Whirlwind',
               21:'Twister',
               25:'Feather Dance',
               29:'Agility',
               33:'Wing Attack',
               37:'Roost',
               41:'Tailwind',
               45:'Mirror Move',
               49:'Flying Press',
               53:'Close Combat',
               54:'Brave Bird',
               },
           'tms' : [
               'Rock Smash',
               'Fly'
               'Strength',
               'Protect',
               ]
           },
       17: {
           'name': 'Wingrudge',
           'type1': 'Flying',
           'type2': 'Fighting',
           'hp':65,
           'atk':85,
           'def':60,
           'spa':35,
           'spd':55,
           'spe':125,
           'sprite':'graphics/sprites/pokemon/017-WINGRUDGE.png',
           'ability':['Scrappy', 'Speed Boost'],
           'itempool':['Focus Sash'],
           'evolution':[[18, 'level', 32]],
           'movepool' : {
               1:'Tackle',
               5:'Sand Attack',
               9:'Mach Punch',
               13:'Quick Attack',
               17:'Whirlwind',
               21:'Twister',
               25:'Feather Dance',
               29:'Agility',
               33:'Wing Attack',
               37:'Roost',
               41:'Tailwind',
               45:'Mirror Move',
               49:'Flying Press',
               53:'Close Combat',
               54:'Brave Bird',
               },
           'tms' : [
               'Rock Smash',
               'Fly'
               'Strength',
               'Protect',
               ]
           },
       18: {
           'name': 'Strikewing',
           'type1': 'Flying',
           'type2': 'Fighting',
           'hp':70,
           'atk':110,
           'def':70,
           'spa':60,
           'spd':63,
           'spe':147,
           'sprite':'graphics/sprites/pokemon/018-STRIKEWING.png',
           'ability':['Scrappy', 'Speed Boost'],
           'itempool':['Focus Sash'],
           'evolution':[['none']],
           'movepool' : {
               1:'Tackle',
               5:'Sand Attack',
               9:'Mach Punch',
               13:'Quick Attack',
               17:'Whirlwind',
               21:'Twister',
               25:'Feather Dance',
               29:'Agility',
               33:'Wing Attack',
               37:'Roost',
               41:'Tailwind',
               45:'Mirror Move',
               49:'Flying Press',
               53:'Close Combat',
               54:'Brave Bird',
               },
           'tms' : [
               'Rock Smash',
               'Fly'
               'Strength',
               'Protect',
               ]
           },
       19: {
           'name': 'Maus',
           'type1': 'Normal',
           'type2': 'None',
           'hp':38,
           'atk':70,
           'def':45,
           'spa':20,
           'spd':45,
           'spe':90,
           'sprite':'graphics/sprites/pokemon/019-MAUS.png',
           'ability':['Absolute Horror'],
           'itempool':['Berry Juice'],
           'evolution':[['none']],
           'movepool' : {
               1:'Tackle',
               2:'Growl',
               4:'Howl',
               9:'Quick Attack',
               11:'Bite',
               15:'Bullet Seed',
               20:'Knock Off',
               29:'Agility',
               33:'Taunt',
               37:'Encore',
               41:'Hyper Voice',
               45:'Mirror Move',
               49:'Double-Edge',
               53:'Big Slam',
               },
           'tms' : [
               'Rock Smash',
               'Fly'
               'Strength',
               'Protect',
               ]
           },
       20: {
           'name': 'Mycedon',
           'type1': 'Bug',
           'type2': 'Ground',
           'hp':100,
           'atk':120,
           'def':100,
           'spa':40,
           'spd':110,
           'spe':40,
           'sprite':'graphics/sprites/pokemon/020-MYCEDON.png',
           'ability':['Scrappy', 'Speed Boost'],
           'itempool':['Moon Stone'],
           'evolution':[[21, 'item', 'Moon Stone']],
           'movepool' : {
               1:'Slash',
               6:'Mud Shot',
               7:'Harden',
               11:'Rage Powder',
               17:'Fury Cutter',
               22:'Magnitude',
               25:'Bug Bite',
               29:'Bulk Up',
               33:'Brick Break',
               37:'Horn Drill',
               41:'Megahorn',
               45:'X-Scissor',
               49:'Earthquake',
               53:'Outrage',
               },
           'tms' : [
               'Rock Smash',
               'Fly'
               'Strength',
               'Protect',
               'Dig',
               ]
           },
       21: {
           'name': 'Myce',
           'type1': 'Bug',
           'type2': 'None',
           'hp':100,
           'atk':10,
           'def':50,
           'spa':10,
           'spd':50,
           'spe':10,
           'sprite':'graphics/sprites/pokemon/021-MYCE.png',
           'ability':['Infest'],
           'itempool':['Quick Claw'],
           'evolution':[['none']],
           'movepool' : {
               1:'Slash',
               5:'Mud Shot',
               6:'Harden',
               20:'Sticky Web',
               23:'Transform',
               25:'Reflect Type',
               27:'Toxic',
               29:'Infestation',
               33:'Suppress', #highest priority and stops opponent from moving (with only 2pp to work with and costs 50%hp)
               },
           'tms' : [
               'Rock Smash',
               'Fly'
               'Strength',
               'Protect',
               ]
           },
       22: {
           'name': 'Magikarp',
           'type1': 'Water',
           'type2': 'None',
           'hp':20,
           'atk':10,
           'def':55,
           'spa':15,
           'spd':20,
           'spe':80,
           'sprite':'graphics/sprites/pokemon/022-MAGIKARP.png',
           'ability':['Swift Swim'],
           'itempool':['Choice Band'],
           'evolution':[[23, 'level', 20]],
           'movepool' : {
               1:'Splash',
               15:'Tackle',
               30:'Flail',
               99:'Dragon Ascent',
               },
           'tms' : [
               'Protect',
               ]
           },
       23: {
           'name': 'Gyarados',
           'type1': 'Water',
           'type2': 'Fire',
           'hp':95,
           'atk':125,
           'def':79,
           'spa':81,
           'spd':60,
           'spe':100,
           'sprite':'graphics/sprites/pokemon/023-GYARADOS.png',
           'ability':['Intimidate', 'Sheer Force'],
           'itempool':['Choice Band'],
           'evolution':[['none']],
           'movepool': {
               1:'Tackle',
               10:'Ember',
               14:'Water Gun',
               17:'Rain Dance',
               18:'Sunny Day',
               21:'Aqua Tail',
               25:'Fire Fang',
               30:'Dragon Dance',
               34:'Hyper Beam',
               38:'Iron Tail',
               48:'Wave Crash',
               50:'Flare Blitz'
               },
           'tms': [
               'Protect',
               'Rock Smash',
               'Strength',
               'Surf',
               'Dive',
               'Flamethrower',
               'Waterfall',
               ]
           }
       }

def get_dex():
    return dex